name: universities_presentation
description: universities presentation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  get_it: 7.6.0
  injectable: 2.1.2
  flutter_bloc: 8.1.2
  freezed_annotation: 2.4.1
  common_presentation:
    path: ../../common/presentation
  universities_domain:
    path: ../domain
  universities_di:
    path: ../di

dev_dependencies:
  build_runner: ^2.1.2
  injectable_generator: 2.1.6
  freezed: 2.4.1





