name: universities_di
description: universities di
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter_bloc: 8.1.2
  common_di:
    path: ../../common/di



