name: common_domain
description: common domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  freezed_annotation: 2.4.1
  equatable: ^2.0.5



dev_dependencies:
  build_runner: ^2.1.2
  freezed: 2.4.1

