name: countries_presentation
description: Common stuff used by other packages
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  get_it: 7.6.0
  injectable: 2.1.2
  bloc: ^8.0.0
  freezed_annotation: 2.4.1
  common_presentation:
    path: ../../common/presentation
  countries_domain:
    path: ../domain

dev_dependencies:
  build_runner: ^2.1.2
  injectable_generator: 2.1.6
  freezed: 2.4.1
  test: ^1.16.0
  bloc_test: ^9.0.0





