name: universities_domain
description: universities domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  get_it: 7.6.0
  injectable: 2.1.2
  common_domain:
    path: ../../common/domain
  universities_di:
    path: ../di

dev_dependencies:
  build_runner: ^2.1.2
  injectable_generator: 2.1.6



