name: countries_di
description: Common stuff used by other packages
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.0.0
  common_di:
    path: ../../common/di



