name: common_presentation
description: common presentation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  freezed_annotation: 2.4.1

dev_dependencies:
  build_runner: ^2.1.2
  freezed: 2.4.1


